bin/git-ignore

Fix typo in in `git ignore` message

---

bin/git-chore
etc/bash_completion.sh
man/git-chore.1
man/git-chore.html
man/git-chore.md

chore command similar to feature/bug/refactor

adding git-chore

---

bin/git-delta
man/git-delta.1
man/git-delta.html
man/git-delta.md

This lists files that differ from a branch (by default all new changes vs. master). One useful application is getting a list of files to check with a lint tool.

Add git-delta

---

bin/git-gh-pages

fix gh-pages to stash and don't delete files

---

Makefile
bin/git-changelog
bin/git-effort
bin/git-rebase-patch
helper/git-extra-utility

now we can put all utility functions to git-extra-utility

extra mktemp into git_extra_mktemp

---

bin/git-fresh-branch

Quick fix for https://github.com/tj/git-extras/issues/142

git-fresh-branch: Check for changes and prompt for input before nuking. (Issue: #142)

---

bin/git-merge-into
man/git-merge-into.1
man/git-merge-into.html
man/git-merge-into.md

add git-merge-into

---

etc/bash_completion.sh

Missed updating bash completions on the first go around.

Updated bash completions for better-changelog.

---

bin/git-delete-merged-branches

when deleting merged branches, preserve "svn" branch for git-svn

---

bin/git-effort

sort unless there is only one item

---

bin/git-guilt
man/git-guilt.1
man/git-guilt.html
man/git-guilt.md

About https://github.com/tj/git-extras/issues/341.
Now we can find someone responsible for an issue.

add git guilt

---

bin/git-ignore

Don't treat ignored patterns as regexps

---

Installation.md

Accoring to the talk in https://github.com/tj/git-extras/issues/371

Install the latest release version of git-extras

---

Commands.md
man/git-line-summary.1
man/git-line-summary.html
man/git-line-summary.md
man/index.txt

Document for git-line-summary

---

Makefile
bin/git-contrib

Two fixes to correct earlier commits

FIXes 'mktemp' to work again on Linux

---

Installation.md
bin/git-extras

For https://github.com/tj/git-extras/issues/379

keep installation silent

---

Installation.md
bin/git-extras
install.sh

installation with curl and bash

---

bin/git-changelog

Handle signals in git-changelog.

---

bin/git-graft
man/git-graft.1
man/git-graft.html
man/git-graft.md

This is a resolved version of #111

graft: Require destination branch. Fix #23

---

man/git-alias.1
man/git-alias.html
man/git-alias.md

Fixes a formatting issue (markdown, lines didn't break).
I ran `manning-up.sh`, which also brought in changes from 9629fdf13c45ba8b9f1c270aa777ebee5585beca where I forgot to run `manning-up.sh`.

alias: docs

---

Commands.md
bin/git-psykorebase
etc/bash_completion.sh
man/git-psykorebase.1
man/git-psykorebase.html
man/git-psykorebase.md

Git psykorebase let your do a rebase without changing the history and with only one conflict handling commit.
See https://github.com/benoitbryon/psykorebase

Add the git-psykorebase command.

---

Installation.md
bin/git-extras
install.cmd

Users can't execute git commands in batch file probably, so I put those git commands into update function.

make it possible to update via `git extras`

---

install.sh

Fixed typo in install.sh

---

Commands.md

* Updated output for `git ignore`
* Added description and examples for `git ignore -g` and `git ignore -l`

Updated documentation for git-ignore

---

bin/git-summary

summary: beware of locale issues, and pass options to line-summary

---

bin/git-effort

Get the purplish color code from here:
https://en.wikipedia.org/wiki/ANSI_escape_code#Colors

use real purplish

---

bin/git-ignore

Add more info how to set global gitignore

---

bin/git-touch

Make `git-touch` behave like `touch` when passed multiple files

---

Installation.md

Add BSD installation instructions.

---

man/git-pr.html

See #506 https://github.com/tj/git-extras/pull/506#issuecomment-173911432

Regerenate git-pr.html

---

Installation.md

:penguin:  Add Ubuntu installation

Add Ubuntu installation

---

bin/git-setup

Hi.  Love git-extras.  What are your thoughts on adding something like this?  I'm happy to make any adjustments necessary. Thanks for your time.

Add -m flag to git-setup to set the initial commit message.

---

Commands.md

update documentation. fix "git ignore-io" flags

---

bin/git-delete-submodule

Update the way to delete submodule

---

bin/git-fork

Fix https://github.com/tj/git-extras/issues/542

fix the support for forking via ssh

---

Installation.md

Fix typo in Installation.md

---

AUTHORS
Commands.md
bin/git-reauthor
etc/bash_completion.sh
man/git-extras.md
man/git-reauthor.1
man/git-reauthor.html
man/git-reauthor.md
man/index.txt

Add new reauthor command: Rewrite history to change author's identity.
Will close issue #518
See the examples within the Commands.md file for some use cases

Add git reauthor

---

Commands.md
bin/git-rename-branch
etc/git-extras-completion.zsh
man/git-rename-branch.1
man/git-rename-branch.html
man/git-rename-branch.md

add rename-branch command

---

bin/git-pr

With these changes, the pr/nn branches created by git-pr also support `git pull` to get PR updates.

Make git-pr set up branch for pulling

---

Commands.md

For the discussion in #576 
To catch up with the release cycle, I submit this pr.
Thanks for the idea from @hozefaj

update docs to clarify rename-branch

---

bin/git-clear

put default option in security-answer to 'no'

fixes #583

---

bin/git-changelog

Show all commit messages if no tag found

---

.travis.yml
check_integrity.sh
etc/git-extras-completion.zsh

I plan to add travis-ci for integrity check later.

Fix integrity for git-reauthor

---

bin/git-clear
bin/git-clear-soft
bin/git-sync

Don't print trailing newline; prompt for yes/no response on the same line

git-{clear,clear-soft,sync}: improve yes/no prompts

---

Makefile
helper/has-git-commit
need_git_commit

Check commit existed before running some commands

---

bin/git-summary

use U+266A instead of comma as separator

---

bin/git-rename-branch

fix syntax & name variables better in rename-branch

---

Commands.md
bin/git-mr
etc/git-extras-completion.zsh
man/git-extras.1
man/git-extras.html
man/git-extras.md
man/git-mr.1
man/git-mr.html
man/git-mr.md
man/index.txt

Just like `git-pr` but for GitLab. :)

Add git-mr to checkout GitLab merge requests

---

not_need_git_repo

as discussed in issue [661](https://github.com/tj/git-extras/issues/661)

Added git-bulk to not_need_git_repo

---

bin/git-pull-request
man/git-pull-request.1
man/git-pull-request.html
man/git-pull-request.md

Add GitHub two factor auth support to git-pull-request

---

man/git-changelog.1
man/git-changelog.html
man/git-changelog.md

Mention how to control changelog format in docs of git-changelog

---

Commands.md
bin/git-release
man/git-release.1
man/git-release.html
man/git-release.md

git-release: add --semver option

---

bin/git-release
man/git-release.1
man/git-release.html
man/git-release.md

git-release: create an empty release commit if there is nothing to commit

---

bin/git-delete-branch

May avoid the demage which hurt @hallzy.
See the discussion in #638

git-delete-branch: avoid deleting local upstream

---

bin/git-sync
man/git-sync.1
man/git-sync.html
man/git-sync.md

Add new option U for git sync.
y: Force sync to remote git repo and clean all untracked files.
N: quit
U: Force sync to remote git repo and do nothing to the untracked files.
Requested in #730 .

feat: Add -s(--soft) for git sync 

---

bin/git-pr
man/git-pr.1
man/git-pr.html
man/git-pr.md

Via `git pr upstream:12345 upstream:12678 upstream:52345`
CC @ZhilkinSerg

git-pr supports pulling multiple pr at once

---

bin/git-guilt

git-guilt: avoid exceeding 80 columns.

---

man/git-reauthor.md

closes #752.
@spacewander please review.

git-reauthor: updated documentation to show rename workaround

---

bin/git-fork

git-fork: prompt for password before 2FA code.

---

bin/git-pr
man/git-pr.1
man/git-pr.html
man/git-pr.md

git-pr: add -m|--merge option to check out a merge commit

---

man/git-pr.1
man/git-pr.html
man/git-pr.md

git-pr: mention the limitation of -m option

---

bin/git-effort

git-effort: adjust column limit according to the paths

---

install.cmd

read COMMANDS_WIHOUT_REPO from not_need_git_repo file

---

Commands.md
bin/git-brv
etc/git-extras-completion.zsh
man/git-brv.1
man/git-brv.html
man/git-brv.md
man/git-extras.md
man/index.txt

This PR adds the git-brv script as proposed in #770.
This script requires bash 4.2, I don't know if this could be an issue.

Fixes #770: Adds git-brv

---

Commands.md
bin/git-browse
etc/bash_completion.sh
etc/git-extras-completion.zsh
man/git-browse.1
man/git-browse.html
man/git-browse.md
man/git-extras.md
man/index.txt

Handles git@server and https://server remotes.
Allows specification of the remote to open
Closes #666
Tested on Linux, WSL and macOS.

Add git-browse command

---

man/git-browse.1
man/git-browse.html
man/git-browse.md

I had the wrong command in the docs 😬

Fix documentation for git-browse

---

CONTRIBUTING.md
Makefile
etc/git-extras.fish

This PR implements completions file for `fish`.
The basis of the commands and short description follows the zsh completion file.

Implement fish completions file

---

man/git-pr.1
man/git-pr.html
man/git-pr.md

git-pr: fix doc format

---

bin/git-bulk

feat: pass origin argument down to git execution

---

man/git-squash.1
man/git-squash.html
man/git-squash.md

Updating the documentation with real option used in the script.

Fixing summary for --squash-msg option.

---

bin/git-delete-tag

feat(delete-tag): get default remote from git config if exists

---

bin/git-ignore
bin/git-ignore-io

Add support for XDG specifications

---

bin/git-browse

[ fix #891 ] Cast branch output if HEAD not exists

---

bin/git-create-branch
bin/git-feature
man/git-create-branch.1
man/git-create-branch.html
man/git-create-branch.md
man/git-feature.1
man/git-feature.html
man/git-feature.md

feat(#861): add optional parameter --from to set the start point

---

Installation.md

This PR fixes some minor issues with the Installation.md

Minor fixes for Installation.md

---

man/git-unlock.1
man/git-unlock.html
man/git-unlock.md

Spell corr in git-unlock synopsis

---

bin/git-ignore

git-ignore: ensure new patterns comes after a newline

---

Commands.md
man/git-summary.1
man/git-summary.html
man/git-summary.md

Thank you for this script :-) I've found it very useful, but not easy to find. Thus, this small docs update suggestion.

Summary: Make path option more prominent

---

bin/git-ignore
bin/git-ignore-io

tweak git-ignore/ignore-io

---

bin/git-browse
bin/git-browse-ci

git-browse/browse-ci: use powershell.exe only when it is available

---

bin/git-standup
man/git-standup.1
man/git-standup.html
man/git-standup.md

Document git standup -w option

---

bin/git-standup
man/git-standup.1
man/git-standup.html
man/git-standup.md

Example of how #963 could be implemented.
If accepted it should be documented and perhaps refactored.

Added config git-extras.standup-implicit-week for git standup

---

bin/git-browse
man/git-browse.1
man/git-browse.html
man/git-browse.md

Ported from
<https://github.com/pbnj/dotfiles/blob/f544dadf8833d6687ac5d8dfc14c59d5890498a7/git/bin/git-browse>
Closes #980

feat(bin/git-browse): open website at file & line number or range

---

bin/git-sync
man/git-sync.1
man/git-sync.html
man/git-sync.md

this further improves use speed to an already epic command.

git-sync --force will sync without interaction

---

bin/git-standup

git standup: work as expected when no configured

---

bin/git-extras

Bump version to 6.6.0-dev

---

Makefile

Makefile: ensure bash is used instead of /bin/sh

---

bin/git-bulk

Fix quite mode of the bulk command

Fix quiet mode of the bulk command

---

bin/git-changelog

Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>

Replace egrep with grep -E

---

Makefile

revert the completion dir change on MacOS

---

Commands.md
bin/git-summary
man/git-summary.1
man/git-summary.html
man/git-summary.md

Simply adds the current branch name to the summary output.

Add the current branch git summary

---

bin/git-cp

Corrected grammar in bin/git-cp:41

Corrected grammar in bin/git-cp

---

Readme.md

Closes #958
Closes #1009 (not enough value)
Closes #366 (stale), closes #348 (stale, not a `git-extras` problem)
Closes #871 (stale, already fixed)

readme: Add alternate screencast URL and improve grammar

---

bin/git-cp

git-cp: continue to merge when merge.ff is only

---

etc/bash_completion.sh
etc/git-extras-completion.zsh
etc/git-extras.fish
etc/test.fish

Closes #819
Closes #106 (stale)
Closes #207 (stale)
Closes #522 (stale)

feat: Implement completion for `git coauthor`

---

Makefile

Introduces a `SKIP_CONFLICT_CHECK` so installs can always be unattended.
- Changes wording of `conflicts with an alias, still install it and idsable the alias? [y/n]`
- Removes the part that says "disable the alias" because any existing aliases aren't (and shouldn't be) disabled
- Adds `test` to the `.PHONY` target
- Improves quoting for paths with spaces
- Improves variable names
And,
- Closes #541
- Closes #375 (stale, built into git)
- Closes #295 (stale, already fixed)
- Closes #968 (stale, out of scope)

makefile: Allow bypassing conflict check

---

tests/conftest.py
tests/helper.py
tests/test_archive_file.py

test(git-archive-file): add unit test

---

bin/git-authors
bin/git-changelog

fix: Use `-iname` and expressions instead of `-iregex`

---

bin/git-extras

Bump version to 7.2.0-dev

---

bin/git-utimes

**Edit:** I tested on a Mac, and this fixes #1118

Fix: patch git-utimes (fixes #1118)

---

.github/workflows/ci.yml

Fix typo in ci.yml

---

bin/git-extras

Bump version to 7.3.0-dev

---

.github/dependabot.yml

Ensure workflows stay up to date.
For all options see https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

ci: add dependabot update for GitHub actions

---

Commands.md

Fix typo in Commands.md

---

bin/git-extras

Bump version to 7.4.0-dev

---

.github/workflows/ci.yml

fix(ci): missing dollar sign

---

AUTHORS
History.md
bin/git-extras

Version 7.4.0

---

bin/git-extras

Bump version to 7.5.0-dev
