bin/git-changelog
GNU mktemp requires at least three X in the last part of template.
=> add enough X to fix #303.

bin/git-authors, etc/bash_completion.sh, man/git-authors.1, man/git-authors.html, man/git-authors.md
A bit like **git-changelog**(1), or **git-summary**(1), but quite different.
Creates a simple list of authors, ordered by number of commits (descending). By default adding it to `/authors|contributors/i`, this can be configured by passing a path in, or omitted by passing in `-l` or `--list`, which would simple write the authors to stdout.
=> Add git-authors

etc/bash_completion.sh
- Introduced in b0a6d04f9ff303a9864070eda45c7309e3789ad4;
- Comments: https://github.com/tj/git-extras/commit/b0a6d04f9ff303a9864070eda45c7309e3789ad4#commitcomment-9687275.
=> Fix missing closing curly brance in `bash_completion.sh`

bin/git-release, man/git-release.md
+ new optional argument "-m" to custom commit message instead of the default commit message.
```bash
git release v1.0.0 -m "+ cusom commit message supports"
```
=> [feature] add custom commit message options supports

bin/git-authors, bin/git-changelog
The editor used will be chosen from the GIT_EDITOR environment variable,
the core.editor configuration variable, the VISUAL environment variable,
or the EDITOR environment variable (in that order).
That ensures that `git-changelog` and `git-authors` will use the same editor
as `git-commit`, `git-merge` etc.
=> use standard git editor in git-authors & git-changelog

bin/git-changelog
Added support for git config:
- `changelog.format` - let's you change the `--pretty` format
- `changelog.opts` - is passed directly to git-log when generating
The idea behind those is that by manipulating global (per machine) and local (per repo) git config you can make `git-changelog` work seamlessly with all the legacy formats people use in various projects.
The defaults remain unchanged - if you don't configure any options, the changelog behaves as it did before those changes.
Also: some  superfluous white-space removal - if it turns our I am seeing things just don't take that commit.
=> changelog config

bin/git-summary
git-summary correctly displays project name when not executed in the top
level directory of a repository.  Fixes tj/git-extras#302.
Uses the git-sh-setup script to find top level directory and then uses
that directory name for the project name.
=> git-summary correctly displays project name

bin/git-setup
When hit `git setup` in an empty directory, it doesn't create a commit. But often we need an empty initial commit for future rebasing and reseting, etc. Fixes #318.
=> Allow empty initial commit when setup repo.

bin/git-feature
This takes any extra arguments supplied to `$git feature` and sets
them as the new feature name. For instances, instead of throwing an
error if `$git feature new thing` is called, it will create branch
`feature/new-thing`.
=> Added in option to concat extra feature names

AUTHORS, bin/git-changelog, man/git-changelog.1, man/git-changelog.html, man/git-changelog.md
This is a complete rewrite of git-changelog to support more functionality. All previous behavior has been retained for backwards compatibility. 
The primary new functionality is centered around support for tag ranges: users can now specify a --start-tag and/or a --final-tag (working backwards, --start-tag is furthest back in history; the --final-tag acts as a stop point). Users can also just specify the --all option to return all commits from now back to the very first commit whether or not tags exist. The --all option can be specified with the --list option to return list format instead of "pretty" format (commits separated by titles--tags/date).
Finally, the --stdout option has been introduced for additional flexibility. This option does exactly what it does everywhere else: sends …
=> Complete rewrite to support commit ranges for pretty and list output.

bin/git-changelog
Fix for when tag and HEAD point to the same commit. Fix for when a branch name appears as a tag (happens when gitflow is used).
Hopefully that's it for now. :)
=> git-changelog fixes

Makefile, bin/git-alias, bin/git-contrib, bin/git-ignore, bin/git-scp, bin/git-squash, etc/bash_completion.sh, helper/reset-env
GNU `grep` always looks for GREP_OPTIONS in the environment, and since
we don't unset it on run, this can result in some issues concerning the
usage of `grep` in scripts. So, we should unset it so nothing strange
can occur.
In addition, strange things can happen if you give `grep` input, and
it interprets it as an argument. So, we should use `--` whenever using
it for patterns that have a chance to be influenced by the user.
=> Prevent strange input and environment variables from causing issues

bin/git-guilt
1. Change the regex `[:digit:]` to `0-9`, make it compatible with mawk.
2. Filter the output of `git blame` and only store the result into tmp file - to reduce the size of tmp file.
3. use `@` as the default value of `until`
=> Hope to fix #341

bin/git-merge-repo, man/git-merge-repo.1, man/git-merge-repo.html, man/git-merge-repo.md
This command merges two repo histories. There's an optional `--squash` flag and an optional "flat merge" mode - if the incoming repo's directory is set to `.`, then a squash-like commit is added for the files added to the current directory.
=> git-merge-repo

bin/git-changelog
Removed dependency on real associative arrays, which are not
support previous to bash 4.
cc: @markeissler
=> Fix git-changelog for compatibility for bash<4. Fixes #337, #338

bin/git-line-summary
'*text' only matches string ended with 'text'. So it matches 'ASCII text', but does not match 'ASCII text executable'. Before, `git summary --line` just counts for plain text file, now we fix it.
=> correct the broken regex

bin/git-changelog
Found it and fixed it. I tested this on:
- CentOS 7
- OSX Bash 4.3.33
- OSX Bash 3.2.57
Output appears to be consistent.
=> Fix git tag substring extraction for bash 3.2.

bin/git-line-summary
1. print format when exist special characters
2. special characters in git blame output
3. exist not committed new files will raise `fatal: no such path 'newfilename' in HEAD`
=> Fix some fatal for git-line-summary

bin/git-effort
It looks "cut" may have different behaviour, e.g. BSD one works the way
git-effort doesn't expect. "awk" looks to be one of possible fixes here.
=> git-effort: replace "wc | cut" with "wc | awk"

Makefile
Some mktemp implementations do not support the `-t` argument. This makes it compatible with both GNU and non-GNU implementations.
=> Makefile: Use a more portable mktemp invocation

Installation.md, install.cmd
The script install.cmd has two environment variables `PREFIX` and `HTMLDIR`.
`PREFIX` is where your git is installed and `HTMLDIR` is the location of html files under `PREFIX`.
This script is written for the latest `Git for Windows 2.x` installed from https://github.com/git-for-windows/git/releases.
Moreover, the executables `colrm.exe` and `column.exe` are needed from [msys2][1]'s installtion directory.
[1]: http://sourceforge.net/projects/msys2/
=> add install.cmd for installation on windows

bin/git-fork
https is usually more preferred nowadays
=> Use https for git-fork

bin/git-effort
Speedup is gained by two main edits
- run effort in parallel
- remove one call to git log (we can use one for both statistics)
This PR will conflict with #390 and/or #391, so I will do a rebase if those are merged.
I have tested this with the Hugo blog engine, with 24 seconds on git effort vs. 7 seconds with this patch. (Those numbers are obviously to be taken with a grain of salt) This was on my computer with two physical cores.
=> [RFC] Improve speed of git effort

bin/git-effort
As said in the issue "When --above is 20, then 20 commits should be gray".
=> effort: Make coloring respect --above. Fix #74

bin/git-changelog
Fixes #395.
`git log` may report `(HEAD -> master, tag:...)` instead of `(HEAD, tag:...)`.
3582b9a$        2015-07-19$      (HEAD -> master, tag: v0.6, tag: lightweight)
This causes changelog to fail:
```
$ git changelog -x -p
fatal: ambiguous argument 'HEAD -> master..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
This PR will fix this issue by matching anything coming after HEAD up to the *first* comma.
=> Catch "HEAD -> master" when creating the changelog

bin/git-effort, etc/bash_completion.sh, man/git-effort.1, man/git-effort.html, man/git-effort.md
Putting this up for discussion.
This makes it possible for `git effort` to take other options other than `--above`.
These get sent to `git log` in effort().
So this is possible now:
`git effort --since="one year ago" --until="one week ago" --above 10 mydir/*`
Invalid options is handled by git log, which I think is nice.
Note though: The original issue wanted to have these options to speed up the process by limiting the commit history, but there is no remarkable performance gain by this as far as I were able to see.  
TODO if this is wanted:
=> [RFC] effort: Allow sending options to log. Fix #326

bin/git-effort
This makes `git effort` able to differentiate between a file that was touched by 1 commit and one that was not touched by a commit.
So if you run  
`git effort --author="Nicolai Skogheim"`  
it will list only files that was touched, and not pretend that every single file has at least one commit touching it.
=> effort: don't count untouched files

bin/git-effort
Just because the output is so massive and ugly if you pass anything other than an integer to `--above`, we should exit early with a message.
=> effort: error out on bad value to --above

Makefile.msys, bin/git-alias, bin/git-changelog, bin/git-extras
This is just bringing @southly's PR up to date.
I am not able to test this myself, so if you run mysysgit, please have a look.
PS: I skipped 91175d73d0a7329e17d473575791f8bf5b0c8ef0 as it seems like 5ee706b585a654dc0339201714dafb267cdcd6b7 fixed that one. But as with the other commits, I will need confirmation from someone able to test this.
=> Portable msysgit

bin/git-effort
=> Make git effort run on FreeBSD

bin/git-contrib
`git contrib` is much more complex than it needs to be.
Moreover, it will now behave like other git commands - output in a pager if that's the default setting for the user, and to STDOUT otherwise.
Also, you could't do `git --no-pager contrib`, but now you can.
I am certain there are even more benefits by doing it this way.  
Edit: Yes, now you can glob on names.
Ex: `git contrib "Nicolai*"`
=> contrib: refactor, and conform to git

bin/git-alias, man/git-alias.md
Showing one alias stopped working after 5b1ac3ccc69f65f8670746f5e0b9c14653cf6685
This removes the double dash that was added.
Also some small alterations on the man page for `git alias` while I were at it.
=> Refactor alias

man/git-contrib.1, man/git-contrib.html, man/git-contrib.md
Add in the docs that `contrib` can match on emails as well as user names, and that the command will return contributions from every user that the search string matches.
=> contrib: update docs

man/git-fork.1, man/git-fork.html, man/git-fork.md
The man page for `git fork` said that `git fork` adds the forked repo as a remote called 'original'.
Change that to upstream, as that is what it actually is called.
=> fork: original->upstream in docs

bin/git-fork
13842de9e0ceb86d6de3ea51fb2740d1e9262819 broke `git fork` since the conversion from ssl to https wasn't finished. git tried to fetch from urls like `https://github.com:user/repo`
This is just replacing those colons with forward slashes.
=> fork: http-urls had colon instead of slash

bin/git-effort
Introduced in cdb773c06 (Fix error on FreeBSD with process substitution)
when trying to squash a bug.
This fix should be valid for that bug as well.
I have no idea how I missed this. But all is well now.
The problem was that for any input, `git effort` would report `active days` to be 1.
=> effort: fix active days always 1

bin/git-effort, man/git-effort.1, man/git-effort.html, man/git-effort.md
In addition to what the title says
- Adjust some of the numbers in one of the examples to be realistic
- Add a note in the docs that the examples omit showing the initial list output by `git effort`, which is the same list, but unsorted.
=> effort: document that it takes any path, not just filenames

bin/git-alias, man/git-alias.1, man/git-alias.1.html, man/git-alias.md
Avoid incorrect usage probably because of the missing quotes, like "git
alias cm checkout master"
=> abort git-alias when too many arguments given.

bin/git-merge-into, man/git-merge-into.1, man/git-merge-into.html, man/git-merge-into.md
Before you merge this: Should we have a special error message for `--ff`? Currently, we print usage if you pass `--ff` to `git merge-into` **with** this patch.
The best would be if we could accept it silently, as it is the default for `git merge`. But that could confuse users who have adapted to use `--ff` with `git merge-into`.
What do you think?
=> merge-into: change --ff option to --ff-only

Makefile
The default task for `make` now is `docs`, just because that task is defined earliest in the file.
This commit sets the default task explicitly to `install`. This is to avoid confusing people who want to build git-extras themselves.
This partially adresses #269
=> Set default make task to be install

Commands.md
Details for:
* Using a remote other than `origin` by providing it in the second parameter.
* Using the `clean` parameter to remove all local `pr/*` branches.
=> Added details to git-pr documentation

bin/git-bug, bin/git-chore, bin/git-feature, bin/git-refactor
And also print checkout info to user.
I think it is no need to conceal checkout message. The message is not unexpected. And when `checkout` is failed(as uncommited change, existed branch, etc.), people can know what happened.
=> remove duplicate checkout

Commands.md, bin/git-feature, man/git-feature.1, man/git-feature.1.html, man/git-feature.md
=> add alias to git-feature

bin/git-effort, man/git-effort.1, man/git-effort.html, man/git-effort.md
This commit does mainly two things:
1. Simplify logic, making it easier to understand the code and add to it
2. Change the synopsis of the command so that we are less likely to be needing to break it later.
Tested only on OSX with Bash 4.3
=> Straighten up effort

bin/git-effort, bin/git-summary
The output of `git log` is not exactly in chronological order. The
default sort option (--date-order) is described in the man page as
follows:
Show no parents before all of its children are shown, but otherwise
show commits in the commit timestamp order.
The `uniq` program will only remove duplicate lines if they follow each
other. In order for this to work correctly, we need to ensure that the
list of dates is exactly in chronological order. There doesn't seem to
be a `git log` option to achieve this, but we can use the `sort`
program. I used reverse sort (`sort -r`) since the output will be roughly
reverse-sorted already.
It's also worth noting that the default --date-order option sorts by
commit date, but git-summary uses *author* date (%ai). Passing
--author-date-order doesn't fix …
=> effort, summary: Correctly estimate the number of active days

Makefile
Since the alias conflict detect need to run `git config --get-regexp 'alias.*'`, and we can't access to git command in the Windows CMD, I just implement the prompt in Makefile.
=> add alias conflict prompt

Commands.md, bin/git-pr
```bash
$ git pr https://github.com/tj/git-extras/pull/453
From https://github.com/tj/git-extras
* [new ref]         refs/pull/453/head -> pr/453
Switched to branch 'pr/453'
```
I'm not experienced in bash hacking, so: feedback appreciated :grin:
=> Add possibility to also checkout pull requests based on GitHub urls

Makefile
Follows up on #383, which introduced a build problem on OS X.
In an `eval` in a `Makefile`, shell variables need to have their `$` escaped as `$$` so they're expanded by the called shell instead of by `make`.
Currently, the build is breaking for me like this.
```
[~/local/opp/git/git-extras on ⇄ master]
$ make PREFIX=/tmp/git-extras install
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
mktemp [-d] [-q] [-u] -t prefix
... installing bins to /tmp/git-extras/bin
... installing man pages to /tmp/git-extras/share/man/man1
usage:	chmod [-fhv] [-R [-H | -L | -P]] [-a | +a | =a  [i][# [ n]]] mode|entry file ...
chmod [-fhv] [-R [-H | -L | -P]] [-E | -C | -N | -i | -I] file ...
make: *** [install] Error 1
[✘ ~/local/opp/git/git-extras on ⇄ master]
$
```
=> Makefile: escape $ used inside eval as shell variable

bin/git-effort
The current code is using hardcoded xterm style escape sequences for its coloring. This switches to using `tput` capabilities, so it'll work with other terminals. More readable, too, IMHO.
Also uses "default color" instead of "black" for the low-activity things, so it still shows up on colorschemes that have dark backgrounds. In my terminals using Solarized Dark, the output wasn't readable.
=> git-effort: use portable terminal escape sequences

Makefile, need_git_repo
Here's a suggestion for refactoring the Makefile to simplify it. This avoids the need for a big repeated block of code for the command-construction logic, where the two blocks differ by only one line.
=> Makefile: refactor is-git-repo inclusion logic

bin/git-line-summary, bin/git-summary
On OS X 10.9.5, I get a couple sed errors in `git-summary-line`.
These look like character encoding issues.
```
[~/local/opp/omz/oh-my-zsh on ⇄ git-extras-compatibility]
$ git-summary --line
project  : oh-my-zsh
sed: RE error: illegal byte sequence
sed: RE error: illegal byte sequence
lines    : 34168
authors  :
3938 Andrew Janke              11.5%
3374 Felipe Contreras          9.9%
```
Running `sed` under `LC_ALL=C` makes the errors go away. This PR does that.
=> git-summary: protect against character encoding issues with LC_ALL=C

install.cmd
That's the same path as cmdr checks when starting up: https://github.com/cmderdev/cmder/blob/master/vendor/init.bat#L31
With this patch you can run `install.cmd` without any arguments. Adding arguments still overwrites the path.
=> Use the default installation path in install.cmd

bin/git-changelog, man/git-changelog.md
using `-m` or `--merges-only` will only show the merge
commit messages. It will also use the body of the merge
commit message in addition to the subject, as github merges
usually have a useless subject line for commit messages.
If used with `-n/--no-merges`, the last one specified will win.
Will need regenerated man pages (.html + .1)
Closes: https://github.com/tj/git-extras/issues/470
=> git-changelog: option to only use merges

Makefile
The current Makefile hardcodes the `/etc` installation location. Users might want to install `etc` files to other places, like `/usr/local/etc` for non-root installs or `brew --prefix` for Homebrew. GNU software and Homebrew locate `SYSCONFDIR` (the conventional Makefile variable for the `/etc` dir location) under `PREFIX` by default, even.
This PR introduces a `SYSCONFDIR` variable to the Makefile to allow the user to customize the `/etc` location. It leaves the default as `/etc`, not changing it to `$(PREFIX)/etc`, so the current default behavior is preserved. I think it's worth discussing whether to change to locate `etc` under `$(PREFIX)` by default; that would allow non-root or fully-relocated installs by just specifying `PREFIX`, and would match the behavior of a lot of other …
=> Makefile: allow customizing of SYSCONFDIR (/etc) location

Makefile, not_need_git_repo
PR #458 inverted the sense of the test for whether is-git-repo should be included in a file. This fixes it.
Fixes #493
=> Makefile: fix inverted list of commands that use is_git_repo

Installation.md, install.cmd
User visible:
* Also accept the git install path (and not the mingw64 subdir) as a user
supplied install location. Make it the new default and warn the user if
a mingw64 dir is supplied (=this dir is not checked, so it might be
anywhere...)
* Find git.exe in path and use that as an install location
* Add error|status messages and output less noise (robocopy)
* do some check if column.exe is not found...
* adjust the installation text for windows...
not user visible:
* more.exe does not work when used in a cmd which has a unicode codepage
-> save the current codepage and set a sane default during the install
* do some "magic" with quotes around path variables -> makes it work with
pathes with spaces in it (both final git dir and the git-extra checkout)
* Do not leak variables to the …
=> Make the win installer more robust

Installation.md, install.cmd
* Fix a regression ("!" needs to be escaped when `enabledelayedexpansion` is used -> this destroyed the shebang line and resulted in not useable commands...)
* check for write rights to the install directory
* add information about column.exe, which will be included in the next Git for Windows release
=> Update windows install.cmd

Commands.md, bin/git-sync, man/git-sync.1, man/git-sync.html, man/git-sync.md
This command syncs local branch with remote branch.
This runs:
```
git fetch <remote-name> <branch-name>
git reset --hard <remote-name>/<branch-name>
git clean -d -f -x
```
=> add git-sync

LICENSE
I am not a lawyer but according to http://www.copyright.gov/circs/circ01.pdf (See screenshot of relevant section below), mentioning the first year of publication in the copyright is a good thing
Mentioning 2010 as the first release happened at that time - https://github.com/tj/git-extras/releases/tag/0.0.1
Also adding `Contributors` to copyright because TJ Holowaychuk is not the only person owning copyright for the whole project. The copyright is collectively owned by all contributors, or more precisely: every contributor owns a copyright on the code he or she has contributed.
The only way to retain full copyright over code is to ask for signing contributor's agreement before merging in changes. This is, in fact, what some companies who license commercially their free software do.
=> Mention initial copyright year and add contributors to copyright

Installation.md
git-extras is available in the official fedora repository: [https://admin.fedoraproject.org/pkgdb/package/rpms/git-extras/](https://admin.fedoraproject.org/pkgdb/package/rpms/git-extras/).
=> Add Fedora package-manager installation instruction

Commands.md, bin/git-standup, man/git-standup.1, man/git-standup.html, man/git-standup.md, not_need_git_repo
For #523
A notable change from the original one: The third argument of the original `git-standup` is `weekstart-weekend`. It is a litttle confusing in my opinion, so I divide it into two seperate arguments: `since` and `until`.
=> add git standup

Commands.md, bin/git-clear, bin/git-clear-soft, man/git-clear-soft.1, man/git-clear-soft.html, man/git-clear-soft.md, man/git-clear.1, man/git-clear.md
This could be one potential solution to issue #531 - a separate command that allows for "soft" cleanup of the repository honoring `.gitignore`.
This PR also includes modified description and notice on `git clear` about that it does not honor `.gitignore`.
I was swinging between this and modifying the existing command with a flag, but this somehow seemed a cleaner solution.
=> Add git clear-soft, modify git clear to indicate explicit removal of files

bin/git-obliterate, man/git-obliterate.1, man/git-obliterate.1.html, man/git-obliterate.md
For https://github.com/tj/git-extras/issues/203
`git obliterate` is (still) dangerous, so don't play with it until you know the full implications.
=> update git obliterate

Installation.md
This bit me on OSX so I've added the note there, but it could also be applied to the whole package manager section if it's also true on other platforms.
=> Add note about overwriting git aliases

bin/git-fork, man/git-fork.1, man/git-fork.html, man/git-fork.md
Update #552 and #553 
* Add git-fork.html removed by accident
* Quote refs by backtick rather than single quote
* Fetch origin after forking
=> Improve forking `origin` repo

bin/git-pull-request
Allows double quotes in JSON. Currently passing double quotes in will output invalid JSON.
Before this change:
```shell
$ json 'Title' 'My PR to "fix" a bug' 'master' 'master'
{
"title": "Title",
"body": "My PR to "fix" a bug",
"head": "master",
"base": "master"
}
```
After this change:
```shell
$ json 'Title' 'My PR to "fix" a bug' 'master' 'master'
{
"title": "Title",
"body": "My PR to \"fix\" a bug",
"head": "master",
"base": "master"
}
```
=> Improve JSON encoding

CONTRIBUTING.md
@hemanth @qw3rtman @nicolaiskogheim 
Let's have a look at this fresh guideline!
=> Add Contributing guideline

AUTHORS
Since there is hesitation about PR #544 this is a quick fix to at least remove my email from the master (google the email in question and you’ll find this repository is the only hit).
=> Remove a non-contributor from AUTHORS

Commands.md, bin/git-fork, man/git-fork.1, man/git-fork.html, man/git-fork.md
Proposed in https://github.com/tj/git-extras/issues/540
This allows you to push changes to your fork without being prompted for your GitHub credentials every time.
Previous behaviour:
```
$ git fork tj/commander.js
Enter your github username
lukechilds
Enter host password for user 'lukechilds':
{
...
}
Cloning into 'commander.js'...
remote: Counting objects: 1791, done.
remote: Total 1791 (delta 0), reused 0 (delta 0), pack-reused 1791
Receiving objects: 100% (1791/1791), 381.24 KiB | 677.00 KiB/s, done.
Resolving deltas: 100% (977/977), done.
Checking connectivity... done.
From https://github.com/tj/commander.js
* [new branch]      gh-pages   -> upstream/gh-pages
* [new branch]      master     -> upstream/master
$ cd commander.js && git push
Username for 'https://github.com':
```
New …
=> Set fork remotes using ssh instead of https

bin/git-missing
Ref #562
This is a rewrite of `git-missing` to make it behave like the docs says it will.
I have tested by running these commands, which should be enough:
```sh
$ git missing feature
$ git missing master feature
$ git missing --no-merges feature
$ git missing --no-merges master feature
$ git missing --no-merges master feature --no-merges
```
That last one may seem stupid, but argument parsing, and especially passing arguments along to other commands in bash can be very tricky, so that one is important. `git log` doesn't care about duplicate arguments, so that's alright.
Only tested on OSX, with bash 4.3.46(1)-release.
I don't think there is anything that would make this crash on other systems, but I will test it on FreeBsd and Arch tomorrow.
___________
Possible future enhancements: …
=> git-missing: do proper argument parsing. Fix #562

man/git-release.1, man/git-release.html, man/git-release.md
=> git-release: fix typo in documentation

bin/git-pull-request, man/git-pull-request.1, man/git-pull-request.html, man/git-pull-request.md
Ref: #546 
Removes the `--global` option to `git config user.email`. This is a saner and more predictable approach.
=> pull-request: should read local config if present

Commands.md, bin/git-repl, man/git-repl.1, man/git-repl.html, man/git-repl.md
This just adds the ability to use `exit` to quit git-repl, in addition to the built-in `quit`.
=> Add built in 'exit' command to git-repl

Commands.md, man/git-repl.1, man/git-repl.html, man/git-repl.md
Ref. https://github.com/tj/git-extras/pull/568#issuecomment-239446250
- Adds proper description
- Adds to and moves example under `Examples` section
- Adds `Option` section
- Updates `Commands.md` with the new text
=> git-repl: improve and clean up docs

Commands.md, bin/git-authors, etc/bash_completion.sh, etc/git-extras-completion.zsh, man/git-authors.1, man/git-authors.html, man/git-authors.md
This feature is used to generate AUTHORS in 4.2.0 release.
=> Add --no-email to git-author

bin/git-changelog
The tempfile was only getting removed if the `-x` parameter was getting set.
This is proved by the following:
````
╰─ ls /tmp/git-changelog.*
/tmp/git-changelog.6HZ  /tmp/git-changelog.Fqc  /tmp/git-changelog.NkI  /tmp/git-changelog.S52  /tmp/git-changelog.xnI
/tmp/git-changelog.dLh  /tmp/git-changelog.Izo  /tmp/git-changelog.nrQ  /tmp/git-changelog.uDx  /tmp/git-changelog.yk5
/tmp/git-changelog.ezr  /tmp/git-changelog.KsF  /tmp/git-changelog.OOO  /tmp/git-changelog.WyK
````
=> Be sure to remove tempfile in git-changelog

Commands.md, bin/git-force-clone, etc/git-extras-completion.zsh, man/git-force-clone.1, man/git-force-clone.html, man/git-force-clone.md
All files for git-force-clone, a command for overwriting local repos when closing repositories.
Provides the basic functionality of `git clone`, but if the destination
repository already exists it will force-reset it to resemble a clone of the
remote.
Because it doesn't actually delete the directory, it is usually significantly
faster than the alternative of deleting the directory and cloning the
repository from scratch.
I've only tested it on my laptop, running Ubuntu 16.04, in bash and zsh.
=> git-force-clone

man/git-squash.1, man/git-squash.html, man/git-squash.md
Fixed a small typo in git-squash documentation.
=> fix: git-squash docs. Replaced 'actual' with 'current'

bin/git-fresh-branch
`break` isn't valid in its current location in the script, resulting in an error like:
/usr/bin/git-fresh-branch: line 42: break: only meaningful in a `for', `while', or `until' loop
Since there's a call to `clean` right at the end of the script, do nothing if anything beginning `Y` or `y` is entered; execution will continue to the end of the script, and `clean` will be called.
=> git-fresh-branch: fix handling of 'yes' response when there are changes

bin/git-delete-merged-branches
Prevents this error:
$ git delete-merged-branches
fatal: branch name required
=> git-delete-merged-branches: use "xargs -r" to prevent error when there are no branches to delete

bin/git-clear-soft
6d49449 changed the `git-clear` default option to "no" (see #583).
Make the `git-clear-soft` default the same - it's safer.
=> git-clear-soft: change default yes/no option to "no" (as with git-clear)

bin/git-sed
Otherwise filenames with spaces result in errors:
$ cat "file with spaces in name"
old
$ git sed old new
sed: can't read file: No such file or directory
sed: can't read with: No such file or directory
sed: can't read spaces: No such file or directory
sed: can't read in: No such file or directory
sed: can't read name: No such file or directory
=> git-sed: use "grep -z" and "xargs -0" to cope with spaces in filenames

bin/git-count
When viewing detailed count information through the usage of the
--all argument, extra arguments would be also passed to the
git shortlog command (probably to be used as revisions list)
This behaviour was introduced in commit 7a60cd1.
Unfortunately the --all argument itself is passed along and results
in the counts of all refs to be displayed
This commit removed the usage of extra arguments and thus only
display the counts of the current branch
=> count: remove usage of extra arguments for detailed display

Commands.md, bin/git-stamp, etc/bash_completion.sh, etc/git-extras-completion.zsh, man/git-stamp.1, man/git-stamp.html, man/git-stamp.md, man/index.txt
Continuing the moving of some of my local git aliases and functions
in order to make them more maintainable and so that other people can use them too :grin:
This adds a new stamp command: Stamp the last commit message
See the [manual](https://github.com/tardypad/git-extras/blob/stamp/man/git-stamp.md) for the use cases and examples
The command is best used afterwards with personal aliases such as `issue = stamp -r Issue`
The usage is then `git issue FOO-142` to stamp the commit with an issue number
=> Add git stamp

bin/git-extras
Replace expr with bash substring expansion, which fixes some syntax error.
Tested under:
GNU bash, version 4.3.42(5)-release (x86_64-pc-msys)
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
=> fix git-extras update and tweak Windows detection

etc/git-extras-completion.zsh, man/git-archive-file.1, man/git-archive-file.html, man/git-archive-file.md, man/git-extras.1, man/git-extras.html, man/git-extras.md
#609 and an occurence of `a identifiable`. 
The `git extras` man page also got updated with an entry for `git reauthor` which probably just was forgotten when it was added.
=> spelling: {a,an} archive

bin/git-fork
Two factor authentication support + minor linting
=> Adds 2FA support to git-fork

bin/git-pull-request
As discussed in #625, `git commit` and friends fall back to environment variable EMAIL when user.email is not set. This PR imports this behavior to git-pull-request.
=> fall back to EMAIL when user.email is not configured

bin/git-effort
The columns in git-effort end up in a mess when you have longer file names.
I have fixed that so the column width matches the longest file in the current git repo.
=> Columns in git-effort adopt to file length

bin/git-pull-request
=> pull_request: should use detected upstream instead of hardcore origin

bin/git-rename-branch
This change will deal with the case in #634 smoothly.
@lagden
Is this what you prefer?
=> use remote detected instead of 'origin' in rename-branch

bin/git-pr
These slashes were causing the branches to be saved in `.git/config` with headings such as `[branch "\"pr/123\""]` as opposed to `[branch "pr/123"]`. This in turn prevented these entries from being removed when running `git pr clean`.
=> Remove slashes from git-config command

Commands.md, bin/git-bulk, etc/git-extras-completion.zsh, man/git-bulk.1, man/git-bulk.html, man/git-bulk.md
This is a new command 'git bulk' that you can use to run commands on multiple repositories within registered workspace. A workspace is a directory that contains multiple git repositories.
I have tested the command on:
- GNU bash, Version 4.4.12(1)-release (x86_64-apple-darwin16.3.0).
- GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin16)
Looking forward to here your feedback on this.
Best regards,
Niklas
=> Git bulk command

Commands.md, bin/git-standup, etc/git-extras-completion.zsh, man/git-standup.1, man/git-standup.html, man/git-standup.md
For issue #645 
Now we can use `-g` option to show GPG info.
@sbriskin
Maybe it is something your want?
Remember to run `git standup` with new style options, for example,
`git standup -a $author -d $days_ago -g`.
=> Upgrade git-standup to new interface

bin/git-stamp
on macOS cat doesn't support the long operator
=> Add BSD cat support

Commands.md, bin/git-release, man/git-release.1, man/git-release.html, man/git-release.md
This pr is based on the work done in #192.
It is expected to fix #650 and other problem.
@breneser
Could you give this branch a try, and confirm whether the problems are fixed?
=> pass tag and optional arguments to hook and stop if pre-release hook fails

bin/git-fork
The next line checks if curl failed, and aborts the script if it has.
This adds the `-f` flag to the curl call, so when the request failed (i.e. when you typed a wrong password), the script aborts appropriately, instead of creating a branch for a non-existent remote.
=> git-fork: Let curl exit with error code on fail

bin/git-delete-merged-branches
Replace GNU only `-r` option.
Try to fix #653
=> git-delete-merged-branches: replace xargs -r option

bin/git-extras
Output said "Setting up 'git-exras" instead of "Setting up 'git-extras"
=> Fix typo in git-extras

bin/git-ignore-io
This makes two improvements to `git ignore-io`:
- Fixes a bug where `git ignore-io -L` omitted entries which did not start with `a..z`
- Removes the arbitrary choice of 5 columns on `git ignore-io -L`, in favour of `column`'s default
=> Improve ignore-io

bin/git-effort
If I understand GNU* correctly, cnorm should be used to undo `civis` (make
invisible). `cvvis` is just another abnormal mode, namely "very visible".
*) https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html
=> git-effort: restore normal (visible) cursor properly

install.cmd
On Windows before setting the code page to 850 the install.cmd script stores the current code page. The current code page is however stored minus the last character, so a current code page '850' will be stored as '85'. This results in the 'Invalid code page' error when trying to restore the code page at the end of the script.
=> Fix 'Invalid code page' error when restoring code page at end of script for Windows

Commands.md
The current docs are incorrect, using the command gives an error msg:
```
error: unknown argument --since=1 week ago
error: if that argument was meant for git-log,
error: please put it after two dashes ( -- ).
```
=> Docs> Add -- in front of cmd for git log

etc/git-extras-completion.zsh
Hi,
this PR addresses #604. Instead of completely overwriting the user-commands variable, we retrieve its value first and we add the additional completion mechanisms later. This is needed when the user has several packages that try to use this completion extension mechanism. With the current code, the last loaded package overwrites the rest.
Regards
=> Preserve existing user commands in zsh completion

bin/git-release
If you are buliding on CircleCI for example, pushing the commits first can lead to a race where CI env will not see the tags since the pull happened before the tags were finished pushing.
It should be fully safe (and backwards-compatible) to change the order of pushing to the remote. This should make integrating with CI tools less of a race.
=> feat(git-release): push tags first to help ci tools not miss them

install.cmd
This fixed `install.cmd` for German Windows distributions.
When executing `CP`, the output is
Aktive Codepage: 850.
Thus, the content of the variable `CP` is
850.
When passing this to `chcp`, the output is
Parameterformat falsch - 850.
Thus, the final lines of the script have no effect.
With this patch, the restore of the old code page works.
=> Remove trailing dot of German Windows

bin/git-summary
Linux column utility will escape tab if a separator is specified.
This problem is first reported in Fedora 27.
May fix #694
=> git-summary: unescape tab for linux column utility

helper/git-extra-utility
Should fix #692 
Not able to test it on OSX and BSD
=> Fixed mktemp template to support busybox (and Alpine linux)

Installation.md
A short section to `Installation.md`. It describes how to install as Zsh plugin. Benefits of such method:
- no administrator access required (easy install on e.g. digital ocean, etc.),
- declarative method of installing – 2 lines in .zshrc lead to git-extras on each account.
=> Installation.md: Zsh-plugin method which doesn't require root access

bin/git-delete-branch
See https://github.com/tj/git-extras/issues/705 for details
=> Fix deleting branches without upstream

bin/git-sed, man/git-sed.md
Discover a separator when the / character is used in arguments.
Prevent running sed when the search pattern does not match any files.
Allow the flags to be passed as a third argument.
=> Improve the git-sed command

bin/git-release
I found 2 bugs when using `git-release --semver`
1. The version regex greedily matches only the first digit for version numbers that contain multiple digits. Matching the multi digit case first solves this problem. 
2. When doing a `major` release, the `minor` and `patch` version numbers should be reset to `0`, and when doing a `minor` release, the `patch` number should be reset to `0`.
=> Fix bugs with git-release --semver

bin/git-sed
The previous workaround is incorrect.
For #632
=> git-sed: fix previous bsd sed workaround

Installation.md
Link to packages, since Arch Linux users may use an AUR helper.
=> Add installation guide for Arch Linux

Commands.md, bin/git-ignore, etc/bash_completion.sh, etc/git-extras-completion.zsh, man/git-ignore.1, man/git-ignore.html, man/git-ignore.md
When working in a repo, it's common to create temporary files -- files that are specific to what you're doing at that very time.
Git has a private ignore file `.git/info/exclude` which isn't replicated.
This is a perfect place to ignore those one-off temporary files.
I've added the option to `git-ignore`, updated the docs and the completion scripts.
I hope you find this useful.
=> add: git-ignore -p (private to repo)

bin/git-changelog
Previously, running "git changelog -x --start-tag 4.5.0 -p -l" will see
```
* Bump version to 4.6.0-dev.  * Version 4.5.0
```
Because there is no newline in the end of each plain output.
=> git-changelog: add missing newline to the plain output

bin/git-changelog, etc/bash_completion.sh, man/git-changelog.1, man/git-changelog.html, man/git-changelog.md
=> git-changelog: add --start-commit option, like --start-tag but for commit

bin/git-rename-branch
Allows the command to work correctly with local branches.
Closes #535
=> git-rename-branch: Don't fail if remote doesn't exist

install.cmd
Changes:
- Added small text line to debug files being written iff environment variable `%DEBUG%` is `true`
- Added option `/E` to both MORE commands used inside install.cmd for copying files.
=> Fix: Dev: `/E` option required to install on Win 10 {b17134} or higher

install.cmd
=> Fix missing double quotes after %DEBUG% in install.cmd

bin/git-standup
Git may fail to detect that the tty supports colors and fallbacks to
non-colored output.
This overrides that by specifying the color parameter.
Based on kamranahmedse/git-standup#84
=> git-standup: ensure color usage

AUTHORS, bin/git-undo, man/git-undo.1, man/git-undo.html, man/git-undo.md
Sometimes it's handy to have the staging area restored when undoing a commit. For example, when you forgot to create a feature branch and accidentally committed to `master`:
```bash
$ git undo -s
$ git checkout -b feature/branch
$ git commit -m 'Use the right branch'
```
The current behavior of "undo [-s|--soft]" is throwing the staging area away. Just like the default without any command line options. With these changes the user is given three distinct choices, listed in the order of destructiveness: 
1. `git undo --soft` (only undo the _commit_)
1. `git undo` (undo both the _commit_ and _staging the changes_) 
1. `git undo --hard` (throw away both the _commit_ and the _related staged changes_)
The implementation is now also straight-forward, more obvious, and easier to understand.
The …
=> Make `git undo -s` restore the staging area

Commands.md, bin/git-rename-remote, etc/git-extras-completion.zsh, man/git-rename-remote.1, man/git-rename-remote.html, man/git-rename-remote.md
I'll add docs and any other relevent stuff if this function is approved
=> git-rename-remote: rename a remote regardless of any existing remotes

Commands.md, bin/git-rename-branch, man/git-rename-branch.1, man/git-rename-branch.html, man/git-rename-branch.md
Now git-rename-branch has the same order like 'git branch -m', 'git
rename-tag' and other rename command.
Note that this is a break change.
Close #759.
=> git-rename-branch: change branch argument order

bin/git-guilt
This does the same fix as tj/git-extras#460.
=> git-guilt: protect against encoding issues with LC_ALL=C

Commands.md, bin/git-coauthor, etc/git-extras-completion.zsh, man/git-coauthor.1, man/git-coauthor.html, man/git-coauthor.md, man/git-extras.md, man/index.txt
This adds a feature to add additional authors to the previous commit,
this feature is supported by GitHub and GitLab and based on the format
should be self-evident to anyone reading the commit message.
This is my first PR to this repo, let me know if I've done something wrong or need to improve the quality of this PR for any reason. Thanks! 🤠
=> Add git coauthor command

Installation.md
This pr change the ice modifier to install completions using zplugin.
=> [Doc]Install completion with zplugin

Installation.md
Add information on how to install `git-extras` in OpenSUSE
=> Docs: add OpenSUSE distribution information

bin/git-ignore
The GIT_DIR environment variable can be used to configure an alternative repository location within GiT. This is very useful i.e. for the management of dotfiles:
```
alias config='GIT_DIR=~/.local/share/dotfiles GIT_WORK_TREE=~ git'
```
This patch replaces the hardcoded `.git` paths in order to make `git ignore -p` command work correctly if GIT_DIR has been set to another location.
=> Use GIT_DIR environment variable to to set .git directory

bin/git-delete-submodule
- Handle case where this is the first submodule, so it leaves the git repository as it was before.
- Handle case where this is the last submodule.
- Check before declaring victory.
- Code reformatting and re-organization. 
- Added option to continue on error to allow cleaning up failed deletions.
NOTE: Not validated on Mac OS X and BSD.
=> Delete empty gitmodules

bin/git-release, etc/git-extras-completion.zsh, man/git-release.1, man/git-release.html, man/git-release.md
This PR adds support for gpg signed tags for the `git-release` command
```git release -s 1```
Will generate a tag `1` signed by the default gpg key
```git release -u key-id 1```
Will generate a tag `1` signed by `key-id`
=> Signed release

bin/git-delete-submodule
This hurted 'git blame' and other git operation which relies on history.
Fix #799.
=> git-delete-submodule: don't remove the history of deleted submodule

bin/git-bulk
This fix is taken from #800.
I did a little modification to resolve conflict.
Thanks @roxchgt for the fix.
=> fix bug in allowedargcount() to not execute command if wrong args count

bin/git-ignore
useful for submodules.
Closes tj/git-extras#807
I'm sorry I don't have much time to test this.
Following CONTRIBUTING.md :
* I cannot test on OSX nor BSD
* I don't know how to check on bash 3.2 that this is valid
* OK for `git 2.1+`
=> git-ignore: support non-default .git directory

check_dependencies.sh
This may not be installed on various systems, and it's difficult to test for the availability of the tool you need, if the check program itself does not exist.
The POSIX 2008 specification mandates the `command -v` builtin; bash is a POSIX 2008 compliant shell, and this builtin has worked since bash 1.x anyway.
A side benefit of using the POSIX portable option is that it requires neither an external disk executable, nor (because unlike "which", the exit code is reliable) a subshell fork. This therefore represents a mild speedup.
=> build: do not require the nonstandard and unpredictable 'which' utility

bin/git-sed
Some special patterns like `n-l`, `[:alpha:]` need to be escaped to avoid
confusing tr.
=> git-sed: escape special characters for tr

bin/git-back, man/git-back.1, man/git-back.html, man/git-back.md
Thanks @vr8hub for the report.
git-back will be removed in the next next release.
=> change: deprecate git-back

bin/git-feature
Per feedback on #834 , here is a one-liner change to fetch a default branch prefix from `git config.`
=> add a config setting for prefix

bin/git-pr
As discussed in #835, a one-liner to fetch a default remote from config.
Testing: 
```bash
$ git remote
origin
upstream
$ git config git-extras.pr.remote "upstream"
$ cat .git/config
<snip>
[git-extras "pr"]
remote = upstream
$ ./bin/git-pr 800
remote: Enumerating objects: 44, done.
remote: Counting objects: 100% (44/44), done.
remote: Total 59 (delta 43), reused 43 (delta 43), pack-reused 15
Unpacking objects: 100% (59/59), 24.49 KiB | 338.00 KiB/s, done.
From github.com:tj/git-extras
* [new ref]         refs/pull/800/head -> pr/800
Switched to branch 'pr/800'
```
=> add a default for the remote to fetch a pr from

etc/git-extras-completion.zsh
Trivial and self-explanatory, minor formatting fixes included.
=> Fix missing newline escapes in git-release zsh completion

bin/git-archive-file, man/git-archive-file.1, man/git-archive-file.html, man/git-archive-file.md
=> git-archive-file: rename invalid chars in the output filename

bin/git-bug, bin/git-chore, bin/git-refactor
Closes #842.
Notably `git-bug` clobbers a very popular other project of the same name.
Having lightweight wrapper scripts clogging up the subcommand namespace
makes it awkward to make use of this project wholesale instead of
piecemeal. These function can be implemented by users with git aliases
very easily.
=> Remove scripts that are mere alias wrappers for git-feature

Installation.md
I guess it's possible to do so for more than 5 years, but the package follows release versions only. Probably it will be useful for someone if it's mentioned explicitly.
=> docs: mention installation via FreeBSD pkg

bin/git-undo
Undo currently does not work when there is only a single commit. There are instances when doing a soft undo on a repository with only a single commit is desired.
In implementing that, I added a few parameter checks, including:
* Cannot specify an undo count greater than the commit count.
* Cannot hard undo all commits, e.g. if commit count is 3, can't hard undo all 3.
* Catch bad parameters, i.e. something other than -s/--soft/-h/--hard as the first parameter or a non-numeric as the second parameter.
Tested on OSX 10.14.6, which is all I have available. I don't believe I used anything that isn't portable, however. (Famous last words.)
=> Modify to work when only a single commit, add parameter checks

man/git-undo.1, man/git-undo.html, man/git-undo.md
The undo documentation has commit count as the first parameter and --soft/hard as the second. The code has the order reversed. This corrects the documentation to match the code.
=> Correct undo documentation to match code order of parameters

bin/git-browse
The `\w` character class on Mac's version of sed (BSD) does not seem to be recognised as "all word characters".
```
echo "foo" | sed -E -e 's/\w*/_/'
_foo
```
I had to update my pattern to `.*` to get it to work correctly. I understand it's not as precise, but I couldn't find a character class that was acknowledged to work the same across all platforms.
=> fix(browse): update sed pattern to work on mac

bin/git-pull-request, man/git-pull-request.1, man/git-pull-request.html, man/git-pull-request.md
Updated the `git pull-request` command to use personal access token instead of basic auth.
=> Updated the git pull-request command to use personal access token instead of basic auth.

Commands.md, bin/git-info, etc/bash_completion.sh, man/git-info.1, man/git-info.html, man/git-info.md
Hi,
I see [#755](https://github.com/tj/git-extras/pull/755), but did something similar in another way
added:
- info about submodules
- colorized headers
- extend info commit and repo configuration
note:
- changes checked in MinGW, Debian Linux
- I do not  update git-extras-completion.zsh (I use bash only, and do not have zsh)
I hope this will be useful
=> Improved the 'git-info' command (color, submodule, config)

bin/git-archive-file, bin/git-delete-merged-branches, bin/git-delta, bin/git-force-clone, bin/git-pull-request, bin/git-show-merged-branches, bin/git-show-unmerged-branches, bin/git-squash, helper/git-extra-utility, man/git-extras.1, man/git-extras.html, man/git-extras.md
=> change: migrate default branch

bin/git-merge-into
Sometimes, if you have dirty env, git checkout fails due to unstashed files.
=> Merge-into: add stash before to checkout

Commands.md, bin/git-utimes, etc/git-extras-completion.zsh, man/git-extras.md, man/git-utimes.1, man/git-utimes.html, man/git-utimes.md, man/index.txt
New tool to change files modification time to their last commit date.
=> git-utimes: Change files modification time to their last commit date

bin/git-summary
Argument starts with '-' can't be committish, so we can safely reject
it.
Fix #898.
=> git-summary: reject invalid option

bin/git-delete-merged-branches
Hi,
When using [`git-worktree`](https://git-scm.com/docs/git-worktree), if a different worktree has a checked out branch (i.e not in the state of detached HEAD), this is what the `git branch` output looks like:
```bash
$ git branch
* develop
+ i-am-a-checked-out-branch-on-a-different-worktree
i-am-another-branch
```
Meaning - `develop` is checked out in the current worktree I'm on, and `i-am-a-checked-out-branch-on-a-different-worktree` is checked out elsewhere.
In any case, we would like to _not_ remove the checked out branch. This is why I filter `+` out.
Have a nice rest of your day,
Matan
=> git-delete-merged-branches: Ignore checked-out branches on different worktrees

Commands.md, bin/git-delete-squashed-branches, etc/bash_completion.sh, etc/git-extras-completion.zsh, etc/git-extras.fish, man/git-delete-squashed-branches.1, man/git-delete-squashed-branches.html, man/git-delete-squashed-branches.md, man/git-extras.md, man/index.txt
Uses https://github.com/not-an-aardvark/git-delete-squashed as a basis for deleting "squashed-merged" branches.
Fixes #858﻿
---
I hope I'm not _too_ far off with this PR.
=> Add `delete-squashed-branches` command

Installation.md
I can confirm it also works Linux. I just installed `git-extras` via `Homebrew` on my Ubuntu machine:
```sh
$ uname -srv
Linux 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021
$ brew install git-extras
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask and homebrew/core).
==> New Formulae
code-minimap              principalmapper           pywhat
==> Updated Formulae
Updated 70 formulae.
==> Updated Casks
Updated 36 casks.
==> Downloading https://ghcr.io/v2/linuxbrew/core/git-extras/manifests/6.2.0
######################################################################## 100.0%
==> Downloading https://ghcr.io/v2/linuxbrew/core/git-extras/blobs/sha256:5a86
==> Downloading from https://pkg-containers.githubusercontent.com/ghcr1/blobs/ …
```
=> Update install doc: Homebrew is not just for macOS

AUTHORS, bin/git-fork, man/git-fork.1, man/git-fork.html, man/git-fork.md
- Removed prompt for OATH Token
- Change prompt from 'password' to 'GitHub Personal Access Token'
=> git-fork | update to match REST-API auth standards as of 2021-06

Commands.md, bin/git-abort, etc/git-extras-completion.zsh, man/git-abort.1, man/git-abort.html, man/git-abort.md, man/git-extras.md, man/index.txt
New subcommand just calls git $op --abort, where $op is current git operation, like rebase
=> Add git-abort

bin/git-lock, bin/git-unlock
Before:
```
$ git lock "filename including spaces.oh"
git-lock: line 37: test: too many arguments
fatal: Unable to mark file filename 
```
After:
```
$ git lock "filename including spaces.oh"
$ git unlock "filename including spaces.oh"
```
=> fix git (un)lock with spaced filenames

bin/git-summary, etc/git-extras-completion.zsh, etc/git-extras.fish, man/git-summary.1, man/git-summary.html, man/git-summary.md
Added option --no-merges to git summary, which excludes merges when counting everything. I've only tested it on Linux, I'd appreciate if someone could help with testing on OSX and BSD.
=> No merge summary

bin/git-summary
SMTP adresses are case insensitive, so --dedup-by-email should treat them as that.
=> Compare email adresses case insensitive in --dedup-by-email

man/git-alias.1, man/git-alias.html, man/git-alias.md, man/git-force-clone.1, man/git-force-clone.html, man/git-force-clone.md, man/git-psykorebase.1, man/git-psykorebase.html, man/git-psykorebase.md, man/git-standup.1, man/git-standup.html, man/git-standup.md
Fixed issues where the synopsis was split in to several paragraphs, or when several command variants was garbled into one line.
=> Format fix of Synopsis in manuals

bin/git-clear, etc/git-extras-completion.zsh, man/git-clear.1, man/git-clear.html, man/git-clear.md
Add a new -f/--force option to git-clear to allow usage in scripts,
or without user input.
Add -h/--help/? for help
Also update the manual for git-clear for these changes.
=> git-clear: add force option

bin/git-ignore
Seems to have been caused by a spelling mistake
=> Fixed bug in git-ignore which ignored config core.excludeFiles

Readme.md, helper/git-extra-utility, man/git-extras.1, man/git-extras.html, man/git-extras.md
Changed according to issue #943 
If the config variable git-extras.default-branch use the value from init.defaultBranch. Also changed the default branch to main.
=> Consider init.defaultBranch in git_extra_default_branch, changed default to main

bin/git-local-commits, man/git-local-commits.1, man/git-local-commits.html, man/git-local-commits.md
The previous version required that the remote branch was in the origin remote. This version uses the upstream branch instead, so it works with any remote. However, it fails if there is no upstream configured. If required, this could be fixed with some checks (i.e. revert to the previous behavior if no upstream is configured.)
=> Made local-commits work with all remotes

bin/git-effort
This is one way to solve issue #953, but it's a little bit flawed.
The problem is that we used `xargs --max-args 1 --replace % -c bash "effort \"%\""`, because the function `effort` only takes one argument and we want it to be quoted. `--max-args` and `--replace` are conflicting in newer versions of xargs.
In this PR I've removed xargs and only use bash code to call `effort`. However, the previous implementation used the `--max-procs=4` option to xargs to use `effort` in four "threads". This version forks heavily, which could cause performance problems in the rest of the system.
I have only done some minor tests in one repo, it should be tested in more repos and on other OS:es as well.
=> Removed xargs from git-effort

Commands.md, bin/git-browse-ci, etc/bash_completion.sh, etc/git-extras-completion.zsh, etc/git-extras.fish, man/git-browse-ci.1, man/git-browse-ci.html, man/git-browse-ci.md, man/git-extras.md, man/index.txt
This is a proposal and an implementation to open repo's CI page (e.g. GitHub Actions, GitLab CI, Bitbucket Pipelines) in default browser.
Feedback is welcome, even if feedback is "thanks, but no thanks".
=> feat: implement git-browse-ci

bin/git-bulk
For git-bulk:
- adds options to use -q or --quiet, causing all non-error git-bulk messages
- sends any git-bulk output to stderr
=> quiet option, errors to stderr

bin/git-release, etc/git-extras-completion.zsh, man/git-release.1, man/git-release.html, man/git-release.md
To allow different release names other than specifically mm.vv.pp, this
adds the ability to use a prefix too.
For example, you can use:
```
$ git release --semver minor --prefix "prefix-"
```
This would allow the previous tags to be in the form `prefix-0.1.0`. A more obvious use case for this would be a single letter, such as `v` or `r` to use tags like: `r0.1.0` or `v0.1.0`.
=> git-release: Add prefix to semver

Installation.md
All links on git.io will stop redirecting after April 29, 2022: https://github.blog/changelog/2022-04-25-git-io-deprecation/
> We will be removing all existing link redirection from git.io on April 29, 2022.
Replace all git.io links with their actual URLs.
=> docs(instllation): replace `git.io`

bin/git-utimes, man/git-utimes.1, man/git-utimes.html, man/git-utimes.md
To fix [issue 971](https://github.com/tj/git-extras/issues/971)
=> update git-utimes.{1,html} to add --newer flag

bin/git-standup, man/git-standup.1, man/git-standup.html, man/git-standup.md
=> #970 standup added -A flag for author date

Makefile
If a bash_completion file should get lazy loaded and is placed in a none standard directory which is listed in XDG_DATA_DIRS it must be placed under share/bash-completion/completions. This is for example used in home-manager.
See https://github.com/scop/bash-completion/blob/730368b35aeb7f9b7eec62ff0e19b1bd8b385961/bash_completion#L2531
=> Fix lazy loading bash_completion from XDG_DATA_DIRS

bin/git-bulk
=> git-bulk: previous refactor redirected $PWD to stderr by mistake

bin/git-cp
fix #985 
The implement https://github.com/tj/git-extras/commit/91b3e47243b8c1ab549cb24a9271fda4a6fdd911 gives a great idea to show the way to reach the goal. I just renew the way to show it clearly.
=> fix(git-cp): keep the history of the files

bin/git-effort
- use wait -n to limit number of processes
requirements:
- OSX, Linux, BSD (You may need to browse their man page)*: 
- use `nproc --all`, `getconf NPROCESSORS_ONLN`, `getconf __NPROCESSORS_ONLN`, `grep -c processor /proc/cpuinfo` to get processor counts.
- provide a fallback value `8`
- Bash 3.2+ (If you aren't sure, see [the Bash changelog](https://www.tldp.org/LDP/abs/html/bash2.html)): 
- `wait -n` was introduced in Bash 4.0
=> fix(git-effort):fork: retry: Resource temporarily unavailable #979

bin/git-abort, man/git-abort.1, man/git-abort.html, man/git-abort.md
If running `git revert <SHA>` results in a conflict, `git abort` will say `I don't know what to abort` because it's not checking `REVERT_HEAD`
=> Include revert conflicts in git abort

bin/git-root
=> git root: show '.' when using with -r in the root dir

Commands.md, etc/git-extras-completion.zsh
missed some more changes in docs/help.. fixup to #992
=> Update docs for git abort change

bin/git-pull-request
We don't actually use the default branch that we print in the prompt (see line 67)
```
printf "  base [%s]: " "$(git_extra_default_branch)" && read -r base
```
=> fix base branch in the pull-request command

bin/git-summary
Currently only the first provided path is processed (`$1`). Therefore it gives incorrect results when multiple paths are given, or even for single bash globs such as `*.py`.
=> Make git-summary accept multiple paths for the --lines argument

bin/git-bulk, bin/git-summary
When you execute
```
git bulk summary
```
it only summarizes the first found repo. 
The reason for it seems to be some stdin ... read ... blah stuff (https://stackoverflow.com/a/13800476/5247292) 
Therefore I changed the way the single repos of the bulk operation are worked off to avoid stdin when in the loop
Fix https://github.com/tj/git-extras/issues/1007
=> Allow to run git-extras within git-bulk

bin/git-summary
Grep 3.8 warns about stray backslashes, so `git summary --line` produces a lot of warnings:
> grep: warning: stray \ before white space
Remove the backslash to get rid of this warning.
=> git-summary: remove stray \ in grep call

Commands.md, bin/git-summary, man/git-summary.1, man/git-summary.html, man/git-summary.md
Add a few more fields to the summary:
```
$ git summary                                                                                                                                                                                   
project     : configservice
repo age    : 3 months
last active : 3 weeks ago  (new)
active on   : 9 days   (renamed from "active" -> "active on")
commits     : 20
files       : 45
uncommitted : 1      (new)
authors     :
8  Michael Mayr   40.0%
5  Simon Gaudek   25.0%
5  guenthgr       25.0%
2  Günther Grill  10.0%
```
=> Add summary fields

bin/git-archive-file, bin/git-authors, bin/git-browse, bin/git-bulk, bin/git-clear
- Uses $() instead of \`\`
- Qutoes variables like paths (branches are skipped over for now because they are forbidden to include whitespace)
- Use `grep -E` instead of deprecated `egrep`
=> chore: Improve quoting and builtin usage

bin/git-changelog, bin/git-commits-since, bin/git-count, bin/git-create-branch, bin/git-delete-squashed-branches, bin/git-effort, bin/git-extras, bin/git-force-clone, bin/git-fork, bin/git-standup, bin/git-sync, brew-release.patch
- Improve quoting, especially in places where filepaths are used
- No longer use `which`, which is deprecated in Debian and has issues - use `command -v` instead
- This ends up **modifying** `brew-release.path` to match (just to note)
- No longer use deprecated `egrep`
- No longer use deprecated `[ -o` or ``
=> chore: More Bash improvements and removing deprecations

Commands.md, bin/git-bulk, bin/git-summary, man/git-summary.1, man/git-summary.html, man/git-summary.md
Fix #1006
This changes allow to print the summary of all the repositories in a table like this:
```
git bulk -q summary --oneline | column -t -s /                                                                                                                                   
Core command "summary" accepted.
keycloak-cxf-admin-client            age: 6 years                last active: 1 year, 2 months ago    active on 4 days      commits: 16      uncommitted: 0
dev-infrastructure-automation        age: 5 weeks                last active: 2 hours ago             active on 8 days      commits: 13      uncommitted: 0
gitlab-project-settings-corrector    age: 3 months               last active: 3 months ago            active on 1 days      commits: 2       uncommitted: 0
gitlab-k8s-cleaner …
```
=> Repo status overview

bin/git-archive-file, bin/git-browse, bin/git-browse-ci, bin/git-bulk, bin/git-create-branch, bin/git-delete-branch, bin/git-delete-squashed-branches, bin/git-delete-tag, bin/git-delta, bin/git-gh-pages, bin/git-merge-repo, bin/git-mr, bin/git-psykorebase, bin/git-release, bin/git-rename-tag, bin/git-repl, bin/git-reset-file, bin/git-scp, bin/git-stamp, bin/git-touch
This mainly fixes the following:
- Not only are more path-related variables quoted (ie. `git-touch`, `git-scp`), but variables like `$BRANCH` are.
- Add more `-r` to `read` invocations
- Stuff like `$(echo $(printf '%s\n' 'thing'))` is changed to `$(printf '%s\n' 'thing')`
=> chore: Fix more Bash inconsistencies

bin/git-bulk
Combine two output lines of the git-bulk command into one for the non-guarded mode.
=> Make the bulk output slimmer

.editorconfig, .github/workflows/ci.yml
While working on #1021, I noticed that some files like [git-delta](https://github.com/tj/git-extras/blob/master/bin/git-delta) don't end in a newline. As a result, that last "line" (`git diff --name-only --diff-filter=$filter $branch`) is not considered part of the text file, according to POSIX.
To fix this, I propose adding an [EditorConfig](https://editorconfig.org) file. When editors read this (some require a plugin like VSCode) file, it adjusts the formatting based on the rules. One thing to note is that rules that specify whitespace are only take affect to each inserted text. For example, with `indent_style = space`, when editing a file that predominately uses tabs, only the spaces will be inserted on each `<tab>` - other characters are not modified.
It seems both 2 and 4-space shell …
=> Add EditorConfig file

Commands.md, bin/git-ignore-io, man/git-ignore-io.1, man/git-ignore-io.html, man/git-ignore-io.md
The original links are now redirected to [Toptal](https://www.toptal.com/developers/gitignore/)
Making this change can save users time redirecting
=> Update gitignore.io urls to Toptal urls

.editorconfig
1. an entry contains multiple filetypes are not supported in some situation
2. our patch already has a newline at the end
3. Makefile should use tab to indent
=> tweak editor config

helper/reset-env
By doing `export GREP_OPTIONS=`, this still creates an environment variable, `GREP_OPTIONS` in all subprocesses called by any of the git-extras scripts.
The `unset -v` has the same effect of removing `GREP_OPTIONS`, without cluttering up the environment table.
=> fix: No longer pollute env with `GREP_OPTIONS`

bin/git-archive-file, bin/git-bulk, bin/git-clear-soft, bin/git-delete-submodule, bin/git-feature, bin/git-fresh-branch, bin/git-graft, bin/git-guilt, bin/git-ignore-io, bin/git-info, bin/git-local-commits, bin/git-magic, bin/git-psykorebase, bin/git-rebase-patch, bin/git-rename-branch, bin/git-rename-remote, bin/git-reset-file, bin/git-scp, bin/git-show-merged-branches, bin/git-show-unmerged-branches, bin/git-stamp, bin/git-standup, bin/git-summary, bin/git-sync, bin/git-undo
They mostly include
- Use `$PWD` instead of `$(pwd)`
- Better quoting
- `[ -n` instead of `[ ! -z`
- Adding `-r` to read
=> chore: Various Bash improvements

bin/git-sed
This pattern existed for backwards compatibility of _ancient_ shells. It is no longer necessary now
=> chore: Remove `X`-style equality comparisons

Commands.md, bin/git-summary, man/git-summary.1, man/git-summary.html, man/git-summary.md
Hi,
I've change the `git summary --oneline` to `git summary  --output-style tabular` which gives an output like this:
```
dev-infrastructure-automation | 8 weeks  | 18 hours ago | 22 days   | 46      | 0
```
When this is combined with the git bulk command, and some other bash magic, then this result can be achieved:
```
$ git bulk -q summary --output-style tabular | sed '1b;/^#/d' | column -t -s "|" -o "|" 
Core command "summary" accepted.
deno-data-handler-prototype       | 9 weeks             | 13 days ago          | 7 days    | 23      | 0
udp-handler                       | 9 weeks             | 2 weeks ago          | 2 days    | 5       | 0
azure-client                      | 9 weeks             | 2 weeks ago          | 2 days    | 4       | 0
dev-infrastructure-automation     | 8 …
```
=> Change the oneline option to a tebular version in the git summary

Makefile
See official conventions: https://docs.freebsd.org/en/books/porters-handbook/special/#shell-completion
=> Makefile: set bash COMPL_DIR to FreeBSD expected defaults

Makefile
We could think of the following use cases:
1. User installs git-extras from official port/pkg. man/man* structure is quite common among different systems, but location of man/ itself can be different. FreeBSD Ports framework setups MANPREFIX to PREFIX by default, i.e. it's /usr/local. The idea is that software may provide different man/man* sections, with final path being /usr/local/man/man*. In contrast, git-extras' Makefile process simplifies the things due to it works with section 1 only, and expects MANPREFIX to be set down to man/man1 path. For this reason, installation via FreeBSD Ports requires unconditional man path configuration like this:
ifeq ($(OS), FreeBSD)
MANPREFIX = "$(PREFIX)/man/man1"
Otherwise, the path will be incorrect. And this is how official FreeBSD port of …
=> Makefile: tune MANPREFIX configuration for FreeBSD

Commands.md, check_integrity.sh, etc/bash_completion.sh
Improve loops and fix typos. Adds a declaration for Shellcheck at the top of the completion file to remove the spurious warning.
=> tweak: Fix typos

bin/git-authors
Just happened to notice this minor typo, figured I'd issue a quick PR.
=> Fix comment typo in git-authors

etc/git-extras-completion.zsh
When I updated the completion file to latest in oh-my-zsh, I found that `gitex_command_successful` was not called as expected. For details, see [oh-my-zsh#71ca386](https://github.com/ohmyzsh/ohmyzsh/commit/71ca38652b039c41ef9b415d0fc05926c37a0bfb)
And also capitalizate github to GitHub
=> Type properly `__gitex_command_successful` calls and capitalizate github to GitHub

bin/git-bulk
1. Previously, if the "repository.txt" file did not end with a blank line, the last entry in the list of repositories was omitted during the cloning process. This limitation has been addressed, and now all repositories listed in the file, including the last one, will be successfully cloned regardless of whether the file ends with a blank line or not.
2. There is support for cloning repositories into custom folder names when using the "repository.txt" file.
repositories\.txt
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
https://host-of-git/repo-1.git Repo-1-Code
https://host-of-git/repo-2.git Repo-2-Code
https://host-of-git/repo-3.git Repo-3-Code
=> I have made two improvements to the git-bulk:

bin/git-ignore, etc/git-extras-completion.zsh, not_need_git_repo
Closes #38
- `git ignore<TAB>` now shows file/directory names
Closes #347
- No longer prints "fatal: not a git repository"-type errors to console. If no (local) Git repository is present, handle gracefully
Closes #427 (stale issue about file that does not exist)
=> Improve `git-ignore` command

bin/git-archive-file
Closes #1067
This makes the base ARCHIVE_NAME for `git-archive-file` to be the name
of the repo root directory instead of the name of the current directory.
=> git archive-file: change base ARCHIVE_NAME

bin/git-psykorebase
Removes the use of `sed` which should address https://github.com/tj/git-extras/issues/856
=> git-psykorebase: determine branch names with bash pattern substitution

bin/git-feature, man/git-feature.1, man/git-feature.html, man/git-feature.md
Closes #1069
This allows the use of a separator other than `/` for feature or other
alias branches. While a command-line option has been provided (`-s` or
`--separator`), this will most often be used via
`git-extras.feature.separator`.
=> git-feature: add configurable branch separator

.github/workflows/ci.yml, .pytest.ini, Makefile, Readme.md, tests/conftest.py, tests/helper.py, tests/test_git_abort.py
=> feat(auto-test): CI with pytest

etc/git-extras-completion.zsh
=> fix: add missing quote in git-extras-completion.zsh

etc/git-extras-completion.zsh
=> fix: Restore zsh completions to working completion

bin/git-alias, man/git-alias.1, man/git-alias.html, man/git-alias.md, tests/helper.py, tests/test_git_alias.py
=> test(git-alias): add its unit test

.github/workflows/ci.yml
The tool requires a more recent version of Go, as per [this commit](https://github.com/editorconfig/editorconfig-core-go/commit/73c37c49c298ff5a605f2a07228f3f99acf3d2d8)
Closes #1085
=> ci: Use Go v1.20 for running `editorconfig-checker`

bin/git-cp
=> Allow `git cp` to create destination folder automatically

CONTRIBUTING.md, Installation.md, Readme.md
Inspired by [this](https://github.com/tj/git-extras/issues/1102#issuecomment-1793283840) comment, this updates the `CONTRIBUTING.md` and moves the information about testing dependencies to itself.
=> Overhaul CONTRIBUTING document

bin/git-utimes
Notes:
1. Works fine with Bash 3.2 using [`shenv`](https://github.com/shenv/shenv).
2. Bash is passed the `—posix` flag to ensure the generated script is POSIX compatible. 
3. The script is compatible with git 2.1, by checking if a post-2.1 flag is supported, before passing it to git.
4. The awk command is passed the `—-posix` flag, too.
Here are some timings running on Ubuntu 23.10:
```
tj/git-extra repo:
This PR: ~83% faster:
real    0m2.863s
user    0m1.799s
sys     0m1.596s
Current code:
real    0m6.151s
user    0m10.673s
sys     0m7.714s
git/git repo:
This PR: ~99% faster:
real    0m28.329s
user    0m41.931s
sys     0m13.390s
Current code:
real    21m23.475s
user    73m27.860s
sys     8m2.065s
torvalds/linux repo:
This PR: ~98% faster
real    11m35.754s
user    11m45.818s
sys …
```
=> feat: Speed up utimes

.editorconfig, .github/workflows/ci.yml, .gitignore, tests/helper.py, tests/test_git_archive_file.py
I started to test @vanpipy's changed on my machines. I think this changes will streamling the testing process for other people as well.
I also wish to close the following issues:
Closes #1083 (spam)
Closes #818 (question answered)
Closes #486 (out of scope)
=> Improve defaults for testing suite

Installation.md
From [this](https://github.com/tj/git-extras/commit/7a65311b1c7e074760c61aa2ebc0f8bd3665bc51#r132308022) comment, some dependencies were missing. I have added more dependencies that are from `util-linux` or require manual installation on some systems.
=> Add more comprensive dependencies

.pytest.ini, Commands.md, bin/git-authors, man/git-authors.1, man/git-authors.html, man/git-authors.md, tests/conftest.py, tests/helper.py, tests/test_authors.py
=> test(git-authors): add unit test

AUTHORS
As requested, I am adding my name to the maintainers category in the AUTHORS file. :)
I wasn't sure if it was alphabetical or chronological order, but it seemed chronological.
=> maintenance: Add my name as maintainer in AUTHORS

bin/git-utimes
**EDIT**: I replaced the double quotes with single quotes to stop bash from processing shell meta-characters, such as `$` and \` in filenames.
**EDIT**: I also removed passing `--posix` to bash, as bash may whine about non-posix code in the user's existing environment. For example, if a user has a function name with a colon in it, bash will complain:
`bash: line 4: BASH_FUNC_lib:funcname%%': not a valid identifier`
when `--posix` is passed.
Now works on repos with tricky filenames:
```
$ git-utimes 
+ touch -h -d@1699829680 "`whoami`"
+ touch -h -d@1699829626 "$USER"
+ touch -h -d@1699829626 $USER
+ touch -h -d@1699829337 "'quotes-and-single-quotes'"
+ touch -h -d@1699829337 '"single-quotes-and-quotes"'
+ touch -h -d@1699829337 a-quote-and-single-quote"'
+ touch -h -d@1699829337 …
```
=> Fix: harden utimes, use single quotes

bin/git-utimes
* Support filenames with backslashes
* Support git functions, such as `function git() { yadm "$@"; }`
* Add Bash's unofficial "strict" mode: set -euo pipefail
* Move awk script to variable (to simplify escaping)
* Add helpful comments
* Shellcheck clean
* Shfmt clean
Here's a test run on Ubuntu 23.10 with git 2.40.1:
```
$ gh repo clone rasa/git-os-test
$ cd git-os-test
$ find -printf '%T+\n' | sort -r | head -n 1
2023-12-11+10:25:22.4594244760
$ git utimes
+ touch -h -d@1699829680 "`whoami`"
+ touch -h -d@1699829626 "$USER"
+ touch -h -d@1699829626 $USER
+ touch -h -d@1699829337 "'quotes-and-single-quotes'"
+ touch -h -d@1699829337 '"single-quotes-and-quotes"'
+ touch -h -d@1699829337 a-quote-and-single-quote"'
+ touch -h -d@1699829337 a-single-quote-and-quote'"
+ touch -h -d@1699828363 …
```
=> fix(utimes): Support filenames with backspaces, etc.

bin/git-utimes
As not all environments have `/dev/stdin`. See https://github.com/ish-app/ish/issues/944
Sorry ‘bout that.
=> fix(utimes): change /dev/stdin to -

.github/workflows/ci.yml, tests/poetry.lock, tests/pyproject.toml, tests/test_git_browse.py
=> test(git-browse): add unit tests

tests/test_git_browse_ci.py
=> test(browse-ci): add unit tests

bin/git-delete-squashed-branches, man/git-delete-squashed-branches.1, man/git-delete-squashed-branches.html, man/git-delete-squashed-branches.md
PR #1134 merged into `master`, instead of `main`. This re-merges those changes back into `main`. I think this has to be "regularly merged" (not squash merge and not rebase merge) so GitHub does not say that [master is 1 commit ahead of `main`](https://github.com/tj/git-extras/tree/master).
=> Add --proceed flag to git-delete-squashed-branches (#1134)

AUTHORS, History.md, bin/git-extras
=> Version 7.2.0

bin/git-summary
If the user has set log.showSignature = ture in gitconfig file, then the `commits` field in the git-summary result is wrong. Replace `git log` with `git rev-list` to avoid the problem, `git rev-list` isn't affected by log.* config parameters, which is also the same as `git-count` command.
---
The result of `git log --oneline HEAD` is as follows, then `| wc -l | tr -d ' '` get wrong count.
```
e34dea9 (origin/main, origin/HEAD) gpg: Signature made Fri May  3 15:52:28 2024 JST
gpg:                using RSA key B5690EEEBB952194
gpg: Can't check signature: No public key
tests: update dependencies (#1142)
3bac05e gpg: Signature made Mon Apr 29 10:59:50 2024 JST
gpg:                using RSA key B5690EEEBB952194
gpg: Can't check signature: No public key
chore(deps): bump …
```
=> fix: git-summary commit count

Commands.md, bin/git-missing, man/git-missing.1, man/git-missing.html, man/git-missing.md
This PR add pathspec support for the `git-missing` command. Users can now limit the commit difference to specific directories or files. Addition is particularly useful for big repositories where users are not concerned with other directories outside their usual workspace.
Pathspec is optional, command will work as usual for users not using it.
```bash
git missing [<first branch>] <second branch> [<git log options>] [[--] <path>...]
```
Compare differences between the current branch and master, limited to the `src/` directory:
```bash
$ git missing master -- src/
< a1b2c3d feat: Add new component in src/
> d4e5f6g fix: Update existing module in src/
```
=> Add pathspec support in `git-missing`

man/git-repl.1, man/git-repl.html, man/git-repl.md
"Lets" is a verb in the present tense third person, while "let's" is short for "let us"
=> Update git-repl.md: typo: "let's" for "lets"

man/git-bulk.1, man/git-bulk.html, man/git-bulk.md
There are many diffs in the derived documents, which I take to be because the last time they were derived was August 2020, on a previous version of ronn, and not because there's a "semantic" difference between the two versions.
=> Update git-bulk.md: use correct stylization in synopsis

man/git-alias.1, man/git-alias.html, man/git-alias.md, man/git-extras.md
Currently these all appear on one line, in the rendered markdown viewer and also in the man page. That isn't what's wanted. What's wanted is for each to be on its own line, which this change implements, using the strategy I found in git-bulk.
Running `make` to generate the new documentation files apparently fixed a typo in another file, as well.
=> Update git-alias.md: add brs to prevent incorrect line behavior

.github/workflows/ci.yml, CONTRIBUTING.md, check_integrity.sh, man/git-extras.1, man/git-extras.html, man/git-extras.md
Before this change, if you changed the documentation in foo.md, check_integrity.sh would not warn you that you had to update foo.html and foo.1. This is bad, because then the derived files could get out of sync. (It also was not checked by the CI, which also just uses check_integrity.sh)
This PR makes 4 changes:
1. check_integrity.sh now tells if you've updated the md since you updated the html and man page, using the file modified times. I got this idea from the tool we use to generate the files, which also checks that, which is why you have to touch the md if you want it to generate fresh derived files.
2. To facilitate the first point, check_integrity.sh now calls our very own `git-utimes --newer` in order to give the files the correct file modified times. This always runs, which has …
=> Use filetimes in check_integrity

check_integrity.sh, man/git-reauthor.1, man/git-reauthor.html, man/git-rebase-patch.1, man/git-rebase-patch.html, man/git-stamp.1, man/git-stamp.html
As I was updating some other code, the check_integrity script informed me that these three files were out of sync... and indeed they were! In the first one, there's a whole new usage pattern documented, and in the others an http has been changed to an https.
It's nice that the script worked now, but why hasn't it worked to prevent this in the CI, such as the recent runs of https://github.com/tj/git-extras/pull/1160 (after the new CI should be in place)? For that matter, why didn't it show up to me locally earlier? Did something else change? Perhaps the --newer flag should be removed from our invocation of git-utimes in check_integrity?
(Perhaps this PR shouldn't be accepted until there is at least one other commit past the CI-altering commit …
=> Update some documentation that was out of sync

Commands.md, bin/git-repl, man/git-repl.1, man/git-repl.html, man/git-repl.md
This makes 3 improvements to git-repl:
- It displays  the exit code of the previous command
- The message at the beginning now tells you how to quit. q ~and x~ have been added as commands that quit
- If git-repl is given arguments, it will be evaluate them as the first command.
Closes #1159
=> Enhance `git-repl`

bin/git-clear
This partially addresses #1167 by making the "deleting files warning" in uppercase characters.
=> Improve warning for `git clear`

bin/git-cp
Change git-cp to use cleaner branch approach, per https://stackoverflow.com/a/46484848/32841 and https://devblogs.microsoft.com/oldnewthing/20190919-00/?p=102904
This approach avoids the need for messy temporary files and therefore eliminates the class of problems related to those--which means that this [resolves #1090]( https://github.com/tj/git-extras/issues/1090).  It also makes for a cleaner history (at least IMHO) and should affect the original branch atomically.
My changes seem to work well for me, but I don't have a great way to test regressions for this fairly significant approach-change.
=> Change git-cp to use cleaner branch approach

bin/git-get
This allows for the removal of any potential trailing forward slash to be propagated into the final dirname.
=> Fix stripping trailing forward slash for git-get

bin/git-fork, bin/git-pull-request, man/git-fork.1, man/git-fork.html, man/git-fork.md, man/git-pull-request.1, man/git-pull-request.html, man/git-pull-request.md
Hi,
`git-fork` & `git-pull-request` currently require to set github token in git config global file.
I would like to keep this file versionned and public on github, so I would prefer not having to put secrets inside.
A common solution to this issue is to pass that token through the `GITHUB_TOKEN` environment variable instead.
Here is a simple commit implementing and documenting that.
ref. #839
=> Support `GITHUB_TOKEN` var for `git-fork` and `git-pull-request`

.github/workflows/ci.yml, tests/conftest.py, tests/helper.py, tests/pyproject.toml, tests/test_git_abort.py, tests/test_git_archive_file.py, tests/test_git_authors.py, tests/test_git_browse.py, tests/test_git_browse_ci.py
Linting the python files in tests directory would reduce whitespace etc change and enforce basic coding standard for those. Kind of opportunistic PR as there might be other opinions about how to deal with this.
=> feat: add ruff linter with ci check

.github/workflows/ci.yml
Seems that ci.yml includes a dead dependency action just to get list of changed files for the PR / push. This seems weird as the repo is all about git. Propose removing this extra dep with straightforward implementation that supports force push for the PR branches.
Also:
- github runners do have `jq` preinstalled, so that was redundant and now no longer needed. 
- separate the install step of the go dependency
=> fix(github-actions): changed files output for editorcondig-checker

Commands.md, bin/git-abort, bin/git-continue, etc/git-extras-completion.zsh, man/git-continue.1, man/git-continue.html, man/git-continue.md, man/git-extras.1, man/git-extras.html, man/git-extras.md, man/index.txt, tests/README.md, tests/conftest.py, tests/helper.py, tests/test_git_continue.py
Also refactor `git-abort` to parse action from the called file name.
There's a promise for this in #865 but that was a long time ago.
=> feat: add git-continue

.github/workflows/ci.yml, bin/git-create-branch, bin/git-fork, bin/git-guilt, bin/git-obliterate, bin/git-repl, bin/git-scp
This was mentioned in some older PR. Autofixes in the same commit, some which seem actual bugs.
=> feat: add shellcheck ci check

bin/git-bulk
Fix a logic error inside the `allowedargcount()` function. This function may be called with one or two arguments. However, no default values are assigned to `$1` and `$2` that are used inside a numerical comparison. Therefore, when using a bad number of arguments for the following lines:
```
listall|purge) allowedargcount 1;;
addcurrent|removeworkspace) allowedargcount 2;;
```
Then, we would get the error `[: : integer expression expected`. To fix this, we assign the 0 default value to `$1` and `$2`, such that we trigger the error message destined to the user without any integer error when there is a bad number of argument and that the function is called with only 1 argument instead of 2.
=> fix(git-bulk): fix a bad integer expression

bin/git-bulk
It may be a bad experience for a user to see a bunch of find errors (*e.g.*, file name too long, no permissions, *etc.*) when using `git-bulk`.  I feel like it is not the job of the tool to report all errors that `find` can throws when searching all files under a hierarchy. Therefore, I quiet the `find` errors by default in this PR. If showing its errors is really on purpose, maybe we could create a flag to do so?
=> fix(git-bulk): quiet find errors by default

Commands.md, bin/git-bulk, man/git-bulk.1, man/git-bulk.html, man/git-bulk.md, man/index.txt
`cd` may fails for multiple reasons:
- mistake when editing `.gitconfig` manually
- previously existing workspace that have been removed
- ...
Currently, if `cd` fails, the `BulkOp` continue its execution ... in the workspace defined in a higher directory that where the user, despite the user specified a specific workspace (`-w`).
The user should be noticed of a failed `cd` (this is really not expected for a valid configuration) and the operations should stop to not execute something unexpected.
=> fix(git-bulk): fix workspace selection when cd fails

etc/git-extras-completion.zsh
Hello there, a simple PR to add the missing Zsh completions which covers the entire `bulk` command. If there is more to do about this before it is merge, let me know! :)
=> docs(git-bulk): Add zsh completion

bin/git-bulk, man/git-bulk.1, man/git-bulk.html, man/git-bulk.md, man/index.txt
Add a new option `--no-follow-symlinks` for `git-bulk` to not traverse symlinks under the workspace directories when searching for git repositories. This PR does not change the default behavior, it only add the option for the user.
=> feat(git-bulk): add new option to no follow symlinks

bin/git-summary, etc/git-extras-completion.zsh, man/git-summary.1, man/git-summary.html, man/git-summary.md, man/index.txt
Add a very simple `--full-path` option to `git-summary` allowing to show the full path of a repository instead of its directory name. This may be useful (or necessary) when you have different repositories with the same name (*e.g.*, same repo on local computer and on a mounted network host or mounted external storage device).
=> Feat: allow git-summary showing full path of repository

bin/git-bulk, etc/git-extras-completion.zsh, man/git-bulk.1, man/git-bulk.html, man/git-bulk.md
Add a new option `--no-follow-hidden` for `git-bulk` to not traverse hidden directories (containing a dot at the beginning) under the workspace directories when searching for git repositories. This PR does not change the default behavior, it only adds the option for the user.
Note that on the implementation, I did not changed the way `find` is searching for directories. Instead, I checked using a regex before performing the operation if we are under a hidden directory. This was the easiest way I found.
=> feat(git-bulk): add new option to not follow hidden directories

.github/workflows/stale.yaml
This closes pull requests after 365 days.
=> Add stale bot for old PRs

.github/workflows/ci.yml, .gitignore, tests/README.md, tests/bin/open, tests/bin/powershell.exe, tests/bin/start, tests/bin/xdg-open, tests/git-alias.bats, tests/git-archive-file.bats, tests/git-authors.bats, tests/git-browse-ci.bats, tests/git-browse.bats, tests/git-continue.bats, tests/test_util.sh
This finalizes the conversion from Pytest to Bats, mostly so coverage can be calculated. Big shoutout to @vanpipy for making the original tests, which made things easier.
Code coverage is mentioned in the testing README.md. I got it to work with bashcov:
```sh
bashcov -- bats ./tests
```
`coverage/index.html` looks like this:
This is what opening a file looks like:
I wasn't able to get kcov to work, unfortunately. If anyone else is able to figure that out, I would appreciate it. But bashcov seems to work fine.
I updated CI to move the Bats testing to a separate job because it speeds things up, testing in parallel.
=> Mostly finish pytest to Bats conversion

.github/workflows/ci.yml, bin/git-abort, bin/git-bulk, bin/git-clear, bin/git-clear-soft, bin/git-ignore, bin/git-merge-into, bin/git-paste, bin/git-psykorebase, bin/git-pull-request, bin/git-rebase-patch, bin/git-release, bin/git-setup, bin/git-standup, bin/git-summary, scripts/checkstyle.py
It can be difficult reading through scripts here with every file seemingly having a different convention (for argument parsing, help menu, function delarations, etc.). This cleans up some of that with a little [checkstyle.py script I made for asdf-vm](https://github.com/asdf-vm/asdf/blob/master/scripts/checkstyle.py) a while back (it has autofix). It catches some things that ShellCheck doesn't, or autofixes things that ShellCheck doesn't.
One thing I would like to do, is add a `chekstyle.py` here, so we can easily enforce those style issues (and possibly other automatically fixable things) for new PRs. Is there interest in that?
=> Format comparisons, functions, and redirections to be consistent

etc/bash_completion.sh
* Add Bash completion for `rename-branch`, `rename-remote` and `remote-tag` commands.
* Remove Bash completion for `rename-file`, which only included `-h` and `--help` options: I find it more sensible to use existing file paths, instead; also, base `git` completion doesn't include `--help` options.
For convenience, this shows the actual changes after the existing functions were sorted alphabetically: https://github.com/danpaolella/git-extras/compare/6e41685...danpaolella:git-extras:bash-completion.
I'm not using Zsh and fish, but I can give a try at those too, if consistency is required.
=> Improvements to Bash completion

man/git-rename-branch.1, man/git-rename-branch.html, man/git-rename-branch.md
Show the option as `<old-branch>` and `<new-branch>` instead of `&lt;old-branch&gt;` and `&lt;new-branch&gt;`.
=> Fix minor typo in `git rename-branch` man page
